# Generated by Django 3.2.6 on 2021-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cognates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=200)),
                ('language_word', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FalseCognates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=200)),
                ('language_word', models.CharField(max_length=200)),
                ('language_definition', models.CharField(max_length=200)),
            ],
        ),
    ]
